# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build get-zap

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    name: Build local
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...

  build-all:
    name: Build all binaries
    runs-on: ubuntu-latest
    env:
      OUTPUT_NAME: get-zap
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - if: matrix.goos == 'windows'
        run: echo "Setting output name to $OUTPUT_NAME"
        env: 
          OUTPUT_NAME: get-zap-${{matrix.goos}}-${{matrix.goarch}}.exe
      - if: matrix.goos != 'windows'
        run: echo "Setting output name to $OUTPUT_NAME"
        env: 
          OUTPUT_NAME: get-zap-${{matrix.goos}}-${{matrix.goarch}}
      - name: Build
        run: GOOS=${{matrix.goos}} GOARCH=${{matrix.goarch}} go build -o bin/${{ env.OUTPUT_NAME }}
      - name: Archive the binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: bin/${{ env.OUTPUT_NAME }}
  
